### PR TITLE
Hi Prahlad

### PR DESCRIPTION
**Pull request by akreienbring**
This may be a blast from the past. I've reworked VisualAlchemist :-)

Have a look and check out if you find my work usefull. Are you still interested in maintaining the project?

Greetings André

### CODE REVIEW

**Comment by ribeiromarcos** [comment]
Hello André,

Yes, your work is certainly useful. I want to contribute, off course.
However, I am Professor at IFMG (Brazil) and I don't have too much free
time. So, I just can offer a small contribution.

Resp.,

======================================================
Marcos Roberto Ribeiro
http://ultramarcosribeiro.blogspot.com
https://sites.google.com/site/ultramarcos/


Em dom., 1 de mar. de 2020 às 15:35, André Kreienbring <
notifications@github.com> escreveu:

**Comment by akreienbring** [comment]
Hello Marcos,

you're welcome :-)
Let's wait and see if Prahlad merges this request and goes on maintaining the software.

**Comment by prahladyeri** [comment]
I no longer maintain this project or work on this. You may continue maintaining and using any forks you may have as long as it conforms to the open source GPLv3 license.

There is no point in merging or accepting any pull requests as this is an abandoned project.

**Comment by akreienbring** [comment]
Hi Prahlad (hope the name is correct...)

The newest version is now hosted here: [https://github.com/akreienbring/dbdesigner](https://github.com/akreienbring/dbdesigner)

Let me thank you again for the great work you did 4 years ago. I was fun picking it up and enhancing it. If you once have the chance to have a look at the current version I would be interested in your feedback! 

André (Greetings from Cologne)

**Pull request closed without merging**
